// resources/js/Data/nationalities.js

const countries = [
    { value: 'Afghanistan', label: 'Afeganistão' },
    { value: 'Albania', label: 'Albânia' },
    { value: 'Algeria', label: 'Argélia' },
    { value: 'American Samoa', label: 'Samoa Americana' },
    { value: 'Andorra', label: 'Andorra' },
    { value: 'Angola', label: 'Angola' },
    { value: 'Anguilla', label: 'Anguila' },
    { value: 'Antigua and Barbuda', label: 'Antígua e Barbuda' },
    { value: 'Argentina', label: 'Argentina' },
    { value: 'Armenia', label: 'Armênia' },
    { value: 'Australia', label: 'Austrália' },
    { value: 'Austria', label: 'Áustria' },
    { value: 'Azerbaijan', label: 'Azerbaijão' },
    { value: 'Bahamas', label: 'Bahamas' },
    { value: 'Bahrain', label: 'Bahrein' },
    { value: 'Bangladesh', label: 'Bangladesh' },
    { value: 'Barbados', label: 'Barbados' },
    { value: 'Belarus', label: 'Bielorrússia' },
    { value: 'Belgium', label: 'Bélgica' },
    { value: 'Belize', label: 'Belize' },
    { value: 'Benin', label: 'Benim' },
    { value: 'Bermuda', label: 'Bermudas' },
    { value: 'Bhutan', label: 'Butão' },
    { value: 'Bolivia', label: 'Bolívia' },
    { value: 'Bosnia and Herzegovina', label: 'Bósnia e Herzegovina' },
    { value: 'Botswana', label: 'Botsuana' },
    { value: 'Brazil', label: 'Brasil' },
    { value: 'British Virgin Islands', label: 'Ilhas Virgens Britânicas' },
    { value: 'Brunei', label: 'Brunei' },
    { value: 'Bulgaria', label: 'Bulgária' },
    { value: 'Burkina Faso', label: 'Burkina Faso' },
    { value: 'Burundi', label: 'Burundi' },
    { value: 'Cambodia', label: 'Camboja' },
    { value: 'Cameroon', label: 'Camarões' },
    { value: 'Canada', label: 'Canadá' },
    { value: 'Cape Verde', label: 'Cabo Verde' },
    { value: 'Cayman Islands', label: 'Ilhas Cayman' },
    { value: 'Central African Republic', label: 'República Centro-Africana' },
    { value: 'Chad', label: 'Chade' },
    { value: 'Chile', label: 'Chile' },
    { value: 'China', label: 'China' },
    { value: 'Colombia', label: 'Colômbia' },
    { value: 'Comoros', label: 'Comores' },
    { value: 'Congo', label: 'Congo' },
    { value: 'Congo (RDC)', label: 'República Democrática do Congo' },
    { value: 'Cook Islands', label: 'Ilhas Cook' },
    { value: 'Costa Rica', label: 'Costa Rica' },
    { value: 'Croatia', label: 'Croácia' },
    { value: 'Cuba', label: 'Cuba' },
    { value: 'Cyprus', label: 'Chipre' },
    { value: 'Czech Republic', label: 'República Tcheca' },
    { value: 'Denmark', label: 'Dinamarca' },
    { value: 'Djibouti', label: 'Djibuti' },
    { value: 'Dominica', label: 'Dominica' },
    { value: 'Dominican Republic', label: 'República Dominicana' },
    { value: 'East Timor', label: 'Timor-Leste' },
    { value: 'Ecuador', label: 'Equador' },
    { value: 'Egypt', label: 'Egito' },
    { value: 'El Salvador', label: 'El Salvador' },
    { value: 'Equatorial Guinea', label: 'Guiné Equatorial' },
    { value: 'Eritrea', label: 'Eritreia' },
    { value: 'Estonia', label: 'Estônia' },
    { value: 'Ethiopia', label: 'Etiópia' },
    { value: 'Faroe Islands', label: 'Ilhas Faroé' },
    { value: 'Fiji', label: 'Fiji' },
    { value: 'Philippines', label: 'Filipinas' },
    { value: 'Finland', label: 'Finlândia' },
    { value: 'France', label: 'França' },
    { value: 'Gabon', label: 'Gabão' },
    { value: 'Gambia', label: 'Gâmbia' },
    { value: 'Georgia', label: 'Geórgia' },
    { value: 'Germany', label: 'Alemanha' },
    { value: 'Ghana', label: 'Gana' },
    { value: 'Gibraltar', label: 'Gibraltar' },
    { value: 'Greece', label: 'Grécia' },
    { value: 'Greenland', label: 'Groenlândia' },
    { value: 'Grenada', label: 'Granada' },
    { value: 'Guam', label: 'Guam' },
    { value: 'Guatemala', label: 'Guatemala' },
    { value: 'Guinea-Bissau', label: 'Guiné-Bissau' },
    { value: 'Guinea', label: 'Guiné' },
    { value: 'Guyana', label: 'Guiana' },
    { value: 'Haiti', label: 'Haiti' },
    { value: 'Honduras', label: 'Honduras' },
    { value: 'Hong Kong', label: 'Hong Kong' },
    { value: 'Hungary', label: 'Hungria' },
    { value: 'Iceland', label: 'Islândia' },
    { value: 'India', label: 'Índia' },
    { value: 'Indonesia', label: 'Indonésia' },
    { value: 'Iran', label: 'Irã' },
    { value: 'Iraq', label: 'Iraque' },
    { value: 'Ireland', label: 'Irlanda' },
    { value: 'Israel', label: 'Israel' },
    { value: 'Italy', label: 'Itália' },
    { value: 'Ivory Coast', label: 'Costa do Marfim' },
    { value: 'Jamaica', label: 'Jamaica' },
    { value: 'Japan', label: 'Japão' },
    { value: 'Jordan', label: 'Jordânia' },
    { value: 'Kazakhstan', label: 'Cazaquistão' },
    { value: 'Kenya', label: 'Quênia' },
    { value: 'Kiribati', label: 'Kiribati' },
    { value: 'Kosovo', label: 'Kosovo' },
    { value: 'Kuwait', label: 'Kuwait' },
    { value: 'Kyrgyzstan', label: 'Quirguistão' },
    { value: 'Laos', label: 'Laos' },
    { value: 'Latvia', label: 'Letônia' },
    { value: 'Lebanon', label: 'Líbano' },
    { value: 'Liberia', label: 'Libéria' },
    { value: 'Libya', label: 'Líbia' },
    { value: 'Liechtenstein', label: 'Liechtenstein' },
    { value: 'Lithuania', label: 'Lituânia' },
    { value: 'Luxembourg', label: 'Luxemburgo' },
    { value: 'Macau', label: 'Macau' },
    { value: 'North Macedonia', label: 'Macedônia do Norte' },
    { value: 'Madagascar', label: 'Madagáscar' },
    { value: 'Malawi', label: 'Malawi' },
    { value: 'Malaysia', label: 'Malásia' },
    { value: 'Maldives', label: 'Maldivas' },
    { value: 'Mali', label: 'Mali' },
    { value: 'Malta', label: 'Malta' },
    { value: 'Marshall Islands', label: 'Ilhas Marshall' },
    { value: 'Martinique', label: 'Martinica' },
    { value: 'Mauritania', label: 'Mauritânia' },
    { value: 'Mauritius', label: 'Maurício' },
    { value: 'Mexico', label: 'México' },
    { value: 'Micronesia', label: 'Micronésia' },
    { value: 'Moldova', label: 'Moldávia' },
    { value: 'Monaco', label: 'Mônaco' },
    { value: 'Mongolia', label: 'Mongólia' },
    { value: 'Montenegro', label: 'Montenegro' },
    { value: 'Montserrat', label: 'Montserrat' },
    { value: 'Morocco', label: 'Marrocos' },
    { value: 'Lesotho', label: 'Lesoto' },
    { value: 'Mozambique', label: 'Moçambique' },
    { value: 'Namibia', label: 'Namíbia' },
    { value: 'Nauru', label: 'Nauru' },
    { value: 'Nepal', label: 'Nepal' },
    { value: 'New Zealand', label: 'Nova Zelândia' },
    { value: 'Nicaragua', label: 'Nicarágua' },
    { value: 'Nigeria', label: 'Nigéria' },
    { value: 'Niger', label: 'Níger' },
    { value: 'Niue', label: 'Niue' },
    { value: 'North Korea', label: 'Coreia do Norte' },
    { value: 'Northern Ireland', label: 'Irlanda do Norte' },
    { value: 'Norway', label: 'Noruega' },
    { value: 'Oman', label: 'Omã' },
    { value: 'Pakistan', label: 'Paquistão' },
    { value: 'Palau', label: 'Palau' },
    { value: 'Palestine', label: 'Palestina' },
    { value: 'Panama', label: 'Panamá' },
    { value: 'Papua New Guinea', label: 'Papua Nova Guiné' },
    { value: 'Paraguay', label: 'Paraguai' },
    { value: 'Peru', label: 'Peru' },
    { value: 'Pitcairn Islands', label: 'Ilhas Pitcairn' },
    { value: 'Poland', label: 'Polônia' },
    { value: 'Portugal', label: 'Portugal' },
    { value: 'Puerto Rico', label: 'Porto Rico' },
    { value: 'Qatar', label: 'Catar' },
    { value: 'Romania', label: 'Romênia' },
    { value: 'Russia', label: 'Rússia' },
    { value: 'Rwanda', label: 'Ruanda' },
    { value: 'Saint Kitts and Nevis', label: 'São Cristóvão e Neves' },
    { value: 'Saint Lucia', label: 'Santa Lúcia' },
    { value: 'Saint Helena', label: 'Santa Helena' },
    { value: 'Saint Vincent and the Grenadines', label: 'São Vicente e Granadinas' },
    { value: 'Samoa', label: 'Samoa' },
    { value: 'San Marino', label: 'San Marino' },
    { value: 'Sao Tome and Principe', label: 'São Tomé e Príncipe' },
    { value: 'Saudi Arabia', label: 'Arábia Saudita' },
    { value: 'Scotland', label: 'Escócia' },
    { value: 'Senegal', label: 'Senegal' },
    { value: 'Serbia', label: 'Sérvia' },
    { value: 'Seychelles', label: 'Seicheles' },
    { value: 'Sierra Leone', label: 'Serra Leoa' },
    { value: 'Singapore', label: 'Singapura' },
    { value: 'Slovakia', label: 'Eslováquia' },
    { value: 'Slovenia', label: 'Eslovênia' },
    { value: 'Solomon Islands', label: 'Ilhas Salomão' },
    { value: 'Somalia', label: 'Somália' },
    { value: 'South Africa', label: 'África do Sul' },
    { value: 'South Korea', label: 'Coreia do Sul' },
    { value: 'South Sudan', label: 'Sudão do Sul' },
    { value: 'Spain', label: 'Espanha' },
    { value: 'Sri Lanka', label: 'Sri Lanka' },
    { value: 'Sudan', label: 'Sudão' },
    { value: 'Suriname', label: 'Suriname' },
    { value: 'Eswatini', label: 'Suazilândia' },
    { value: 'Sweden', label: 'Suécia' },
    { value: 'Switzerland', label: 'Suíça' },
    { value: 'Syria', label: 'Síria' },
    { value: 'Taiwan', label: 'Taiwan' },
    { value: 'Tajikistan', label: 'Tajiquistão' },
    { value: 'Tanzania', label: 'Tanzânia' },
    { value: 'Thailand', label: 'Tailândia' },
    { value: 'Togo', label: 'Togo' },
    { value: 'Tonga', label: 'Tonga' },
    { value: 'Trinidad and Tobago', label: 'Trindade e Tobago' },
    { value: 'Tristan da Cunha', label: 'Tristão da Cunha' },
    { value: 'Tunisia', label: 'Tunísia' },
    { value: 'Turkey', label: 'Turquia' },
    { value: 'Turkmenistan', label: 'Turcomenistão' },
    { value: 'Turks and Caicos Islands', label: 'Ilhas Turks e Caicos' },
    { value: 'Tuvalu', label: 'Tuvalu' },
    { value: 'Uganda', label: 'Uganda' },
    { value: 'Ukraine', label: 'Ucrânia' },
    { value: 'Uruguay', label: 'Uruguai' },
    { value: 'Uzbekistan', label: 'Uzbequistão' },
    { value: 'Vatican City', label: 'Vaticano' },
    { value: 'Vanuatu', label: 'Vanuatu' },
    { value: 'Venezuela', label: 'Venezuela' },
    { value: 'Vietnam', label: 'Vietnã' },
    { value: 'Wallis and Futuna', label: 'Wallis e Futuna' },
    { value: 'Wales', label: 'País de Gales' },
    { value: 'Yemen', label: 'Iémen' },
    { value: 'Zambia', label: 'Zâmbia' },
    { value: 'Zimbabwe', label: 'Zimbábue' },
];

export default countries;
